.PHONY: default
default: all ;


indices.html:
	wget -O indices.html https://html.spec.whatwg.org/multipage/indices.html

dom.html:
	wget -O dom.html https://html.spec.whatwg.org/multipage/dom.html

input.html:
	wget -O input.html https://html.spec.whatwg.org/multipage/input.html

spec: indices.html dom.html input.html

all: spec

